export const class_time_table = [
  {
    day: "Mon",
    start_time: "09:00 AM",
    end_time: "10:00 AM",
    subject: "Data Structures",
    class: "CSE",
    year: 2,
    semester: 4,
    section: "A",
  },
  {
    day: "Mon",
    start_time: "10:00 AM",
    end_time: "11:00 AM",
    subject: "Operating Systems",
    class: "CSE",
    year: 3,
    semester: 6,
    section: "B",
  },
  {
    day: "Mon",
    start_time: "11:00 AM",
    end_time: "12:00 PM",
    subject: "Computer Networks",
    class: "CSE",
    year: 4,
    semester: 8,
    section: "C",
  },
  {
    day: "Tue",
    start_time: "09:00 AM",
    end_time: "10:00 AM",
    subject: "Algorithms",
    class: "CSE",
    year: 2,
    semester: 4,
    section: "A",
  },
  {
    day: "Tue",
    start_time: "10:00 AM",
    end_time: "11:00 AM",
    subject: "Database Systems",
    class: "CSE",
    year: 3,
    semester: 6,
    section: "B",
  },
  {
    day: "Tue",
    start_time: "11:00 AM",
    end_time: "12:00 PM",
    subject: "Artificial Intelligence",
    class: "CSE",
    year: 4,
    semester: 8,
    section: "C",
  },
  {
    day: "Wed",
    start_time: "09:00 AM",
    end_time: "10:00 AM",
    subject: "Software Engineering",
    class: "CSE",
    year: 2,
    semester: 4,
    section: "A",
  },
  {
    day: "Wed",
    start_time: "10:00 AM",
    end_time: "11:00 AM",
    subject: "Web Technologies",
    class: "CSE",
    year: 3,
    semester: 6,
    section: "B",
  },
  {
    day: "Wed",
    start_time: "11:00 AM",
    end_time: "12:00 PM",
    subject: "Machine Learning",
    class: "CSE",
    year: 4,
    semester: 8,
    section: "C",
  },
  {
    day: "Thu",
    start_time: "09:00 AM",
    end_time: "10:00 AM",
    subject: "Discrete Mathematics",
    class: "CSE",
    year: 1,
    semester: 2,
    section: "A",
  },
  {
    day: "Thu",
    start_time: "10:00 AM",
    end_time: "11:00 AM",
    subject: "Compiler Design",
    class: "CSE",
    year: 3,
    semester: 6,
    section: "B",
  },
  {
    day: "Thu",
    start_time: "11:00 AM",
    end_time: "12:00 PM",
    subject: "Cyber Security",
    class: "CSE",
    year: 4,
    semester: 8,
    section: "C",
  },
  {
    day: "Fri",
    start_time: "09:00 AM",
    end_time: "10:00 AM",
    subject: "Introduction to Programming",
    class: "CSE",
    year: 1,
    semester: 2,
    section: "A",
  },
  {
    day: "Fri",
    start_time: "10:00 AM",
    end_time: "11:00 AM",
    subject: "Software Testing",
    class: "CSE",
    year: 3,
    semester: 6,
    section: "B",
  },
  {
    day: "Fri",
    start_time: "11:00 AM",
    end_time: "12:00 PM",
    subject: "Cloud Computing",
    class: "CSE",
    year: 4,
    semester: 8,
    section: "C",
  },
  {
    day: "Sat",
    start_time: "09:00 AM",
    end_time: "10:00 AM",
    subject: "Computer Organization",
    class: "CSE",
    year: 2,
    semester: 4,
    section: "A",
  },
  {
    day: "Sat",
    start_time: "10:00 AM",
    end_time: "11:00 AM",
    subject: "Theory of Computation",
    class: "CSE",
    year: 3,
    semester: 6,
    section: "B",
  },
  {
    day: "Sat",
    start_time: "11:00 AM",
    end_time: "12:00 PM",
    subject: "Data Mining",
    class: "CSE",
    year: 4,
    semester: 8,
    section: "C",
  },
];
