export const faculty_ratings = [
  {
    id:1,
    name: "Praveen Nayak",
    employee_id: "CSE12345678",
    date_of_join: "Jan 1, 2020",
    subject: "Physics",
    class: ["CSE-A - 1st year", "CSE-C - 1st year"],
    rating: 4.7,
  },
  {
    id:2,
    name: "Praveen Nayak",
    employee_id: "CSE12345678",
    date_of_join: "Jan 1, 2020",
    subject: "Physics",
    class: ["CSE-A - 1st year", "CSE-C - 1st year"],
    rating: 4.7,
  },
  {
    id:3,
    name: "Praveen Nayak",
    employee_id: "CSE12345678",
    date_of_join: "Jan 1, 2020",
    subject: "Physics",
    class: ["CSE-A - 1st year", "CSE-C - 1st year"],
    rating: 4.7,
  },
  {
    id:4,
    name: "Praveen Nayak",
    employee_id: "CSE12345678",
    date_of_join: "Jan 1, 2020",
    subject: "Physics",
    class: ["CSE-A - 1st year", "CSE-C - 1st year"],
    rating: 4.7,
  },
  {
    id:5,
    name: "Praveen Nayak",
    employee_id: "CSE12345678",
    date_of_join: "Jan 1, 2020",
    subject: "Physics",
    class: ["CSE-A - 1st year", "CSE-C - 1st year"],
    rating: 4.7,
  },
  {
    id:6,
    name: "Praveen Nayak",
    employee_id: "CSE12345678",
    date_of_join: "Jan 1, 2020",
    subject: "Physics",
    class: ["CSE-A - 1st year", "CSE-C - 1st year"],
    rating: 4.7,
  },
  {
    id:7,
    name: "Praveen Nayak",
    employee_id: "CSE12345678",
    date_of_join: "Jan 1, 2020",
    subject: "Physics",
    class: ["CSE-A - 1st year", "CSE-C - 1st year"],
    rating: 4.7,
  },
  {
    id:8,
    name: "Praveen Nayak",
    employee_id: "CSE12345678",
    date_of_join: "Jan 1, 2020",
    subject: "Physics",
    class: ["CSE-A - 1st year", "CSE-C - 1st year"],
    rating: 4.7,
  },
  {
    id:9,
    name: "Praveen Nayak",
    employee_id: "CSE12345678",
    date_of_join: "Jan 1, 2020",
    subject: "Physics",
    class: ["CSE-A - 1st year", "CSE-C - 1st year"],
    rating: 4.7,
  },
  {
    id:10,
    name: "Praveen Raj",
    employee_id: "CSE12345678",
    date_of_join: "Jan 1, 2020",
    subject: "Physics",
    class: ["CSE-A - 1st year", "CSE-C - 1st year"],
    rating: 4.7,
  },
  
];
