import { RubricData } from "../models/apiModels";

export const rubric_data: RubricData = {
  id: "rubric_001",
  serial_id: 1,
  created_at: "2024-05-25T10:00:00Z",
  updated_at: "2024-05-25T10:00:00Z",
  meta_data: {},
  rubric_meta: {} as any,
  published: true,
  created_by: "admin",
  title: "Sample Rubric",
  name: "Project Evaluation Rubric",
  ratings: [
    {
      id: "rating_1",
      serial_id: 1,
      created_at: "2024-05-25T10:00:00Z",
      updated_at: "2024-05-25T10:00:00Z",
      title: "Excellent",
      value: 4,
      index: 0,
      rubric_id: "rubric_001",
      created_by: "admin",
    },
    {
      id: "rating_2",
      serial_id: 2,
      created_at: "2024-05-25T10:00:00Z",
      updated_at: "2024-05-25T10:00:00Z",
      title: "Good",
      value: 3,
      index: 1,
      rubric_id: "rubric_001",
      created_by: "admin",
    },
    {
      id: "rating_3",
      serial_id: 3,
      created_at: "2024-05-25T10:00:00Z",
      updated_at: "2024-05-25T10:00:00Z",
      title: "Fair",
      value: 2,
      index: 2,
      rubric_id: "rubric_001",
      created_by: "admin",
    },
    {
      id: "rating_4",
      serial_id: 4,
      created_at: "2024-05-25T10:00:00Z",
      updated_at: "2024-05-25T10:00:00Z",
      title: "Poor",
      value: 1,
      index: 3,
      rubric_id: "rubric_001",
      created_by: "admin",
    },
  ],
  criterias: [
    {
      id: "criteria_1",
      serial_id: 1,
      created_at: "2024-05-25T10:00:00Z",
      updated_at: "2024-05-25T10:00:00Z",
      criteria: "Content Quality",
      weightage: 100,
      rubric_id: "rubric_001",
      created_by: "admin",
      index: 0,
      course_outcome_tags: ["CO1"],
      performance_descriptors: [
        {
          id: "pd_1",
          serial_id: 1,
          created_at: "2024-05-25T10:00:00Z",
          updated_at: "2024-05-25T10:00:00Z",
          performance_descriptor: "Thorough and insightful analysis",
          rubric_id: "rubric_001",
          index: 0,
          rubric_criteria_id: "criteria_1",
          rubric_performance_rating_id: "rating_1",
          created_by: "admin",
        },
        {
          id: "pd_2",
          serial_id: 2,
          created_at: "2024-05-25T10:00:00Z",
          updated_at: "2024-05-25T10:00:00Z",
          performance_descriptor: "Good analysis with minor gaps",
          rubric_id: "rubric_001",
          index: 1,
          rubric_criteria_id: "criteria_1",
          rubric_performance_rating_id: "rating_2",
          created_by: "admin",
        },
        {
          id: "pd_3",
          serial_id: 3,
          created_at: "2024-05-25T10:00:00Z",
          updated_at: "2024-05-25T10:00:00Z",
          performance_descriptor: "Basic analysis with several gaps",
          rubric_id: "rubric_001",
          index: 2,
          rubric_criteria_id: "criteria_1",
          rubric_performance_rating_id: "rating_3",
          created_by: "admin",
        },
        {
          id: "pd_4",
          serial_id: 4,
          created_at: "2024-05-25T10:00:00Z",
          updated_at: "2024-05-25T10:00:00Z",
          performance_descriptor: "Poor or lacking analysis",
          rubric_id: "rubric_001",
          index: 3,
          rubric_criteria_id: "criteria_1",
          rubric_performance_rating_id: "rating_4",
          created_by: "admin",
        },
      ],
    },
    {
      id: "criteria_2",
      serial_id: 2,
      created_at: "2024-05-25T10:00:00Z",
      updated_at: "2024-05-25T10:00:00Z",
      criteria: "Organization",
      weightage: 100,
      rubric_id: "rubric_001",
      created_by: "admin",
      index: 1,
      course_outcome_tags: ["CO2"],
      performance_descriptors: [
        {
          id: "pd_5",
          serial_id: 5,
          created_at: "2024-05-25T10:00:00Z",
          updated_at: "2024-05-25T10:00:00Z",
          performance_descriptor: "Well-organized and logical flow",
          rubric_id: "rubric_001",
          index: 0,
          rubric_criteria_id: "criteria_2",
          rubric_performance_rating_id: "rating_1",
          created_by: "admin",
        },
        {
          id: "pd_6",
          serial_id: 6,
          created_at: "2024-05-25T10:00:00Z",
          updated_at: "2024-05-25T10:00:00Z",
          performance_descriptor: "Mostly organized with minor issues",
          rubric_id: "rubric_001",
          index: 1,
          rubric_criteria_id: "criteria_2",
          rubric_performance_rating_id: "rating_2",
          created_by: "admin",
        },
        {
          id: "pd_7",
          serial_id: 7,
          created_at: "2024-05-25T10:00:00Z",
          updated_at: "2024-05-25T10:00:00Z",
          performance_descriptor: "Somewhat organized with noticeable issues",
          rubric_id: "rubric_001",
          index: 2,
          rubric_criteria_id: "criteria_2",
          rubric_performance_rating_id: "rating_3",
          created_by: "admin",
        },
        {
          id: "pd_8",
          serial_id: 8,
          created_at: "2024-05-25T10:00:00Z",
          updated_at: "2024-05-25T10:00:00Z",
          performance_descriptor: "Poorly organized and difficult to follow",
          rubric_id: "rubric_001",
          index: 3,
          rubric_criteria_id: "criteria_2",
          rubric_performance_rating_id: "rating_4",
          created_by: "admin",
        },
      ],
    },
    {
      id: "criteria_3",
      serial_id: 3,
      created_at: "2024-05-25T10:00:00Z",
      updated_at: "2024-05-25T10:00:00Z",
      criteria: "Clarity of Presentation",
      weightage: 100,
      rubric_id: "rubric_001",
      created_by: "admin",
      index: 2,
      course_outcome_tags: ["CO3"],
      performance_descriptors: [
        {
          id: "pd_9",
          serial_id: 9,
          created_at: "2024-05-25T10:00:00Z",
          updated_at: "2024-05-25T10:00:00Z",
          performance_descriptor: "Clear and engaging presentation",
          rubric_id: "rubric_001",
          index: 0,
          rubric_criteria_id: "criteria_3",
          rubric_performance_rating_id: "rating_1",
          created_by: "admin",
        },
        {
          id: "pd_10",
          serial_id: 10,
          created_at: "2024-05-25T10:00:00Z",
          updated_at: "2024-05-25T10:00:00Z",
          performance_descriptor: "Clear presentation with minor issues",
          rubric_id: "rubric_001",
          index: 1,
          rubric_criteria_id: "criteria_3",
          rubric_performance_rating_id: "rating_2",
          created_by: "admin",
        },
        {
          id: "pd_11",
          serial_id: 11,
          created_at: "2024-05-25T10:00:00Z",
          updated_at: "2024-05-25T10:00:00Z",
          performance_descriptor: "Somewhat clear but lacks engagement",
          rubric_id: "rubric_001",
          index: 2,
          rubric_criteria_id: "criteria_3",
          rubric_performance_rating_id: "rating_3",
          created_by: "admin",
        },
        {
          id: "pd_12",
          serial_id: 12,
          created_at: "2024-05-25T10:00:00Z",
          updated_at: "2024-05-25T10:00:00Z",
          performance_descriptor: "Unclear and unengaging presentation",
          rubric_id: "rubric_001",
          index: 3,
          rubric_criteria_id: "criteria_3",
          rubric_performance_rating_id: "rating_4",
          created_by: "admin",
        },
      ],
    },
    {
      id: "criteria_4",
      serial_id: 4,
      created_at: "2024-05-25T10:00:00Z",
      updated_at: "2024-05-25T10:00:00Z",
      criteria: "Use of Resources",
      weightage: 100,
      rubric_id: "rubric_001",
      created_by: "admin",
      index: 3,
      course_outcome_tags: ["CO4"],
      performance_descriptors: [
        {
          id: "pd_13",
          serial_id: 13,
          created_at: "2024-05-25T10:00:00Z",
          updated_at: "2024-05-25T10:00:00Z",
          performance_descriptor: "Excellent use of diverse resources",
          rubric_id: "rubric_001",
          index: 0,
          rubric_criteria_id: "criteria_4",
          rubric_performance_rating_id: "rating_1",
          created_by: "admin",
        },
        {
          id: "pd_14",
          serial_id: 14,
          created_at: "2024-05-25T10:00:00Z",
          updated_at: "2024-05-25T10:00:00Z",
          performance_descriptor: "Good use of resources with minor gaps",
          rubric_id: "rubric_001",
          index: 1,
          rubric_criteria_id: "criteria_4",
          rubric_performance_rating_id: "rating_2",
          created_by: "admin",
        },
        {
          id: "pd_15",
          serial_id: 15,
          created_at: "2024-05-25T10:00:00Z",
          updated_at: "2024-05-25T10:00:00Z",
          performance_descriptor: "Basic use of resources with several gaps",
          rubric_id: "rubric_001",
          index: 2,
          rubric_criteria_id: "criteria_4",
          rubric_performance_rating_id: "rating_3",
          created_by: "admin",
        },
        {
          id: "pd_16",
          serial_id: 16,
          created_at: "2024-05-25T10:00:00Z",
          updated_at: "2024-05-25T10:00:00Z",
          performance_descriptor: "Poor or lacking use of resources",
          rubric_id: "rubric_001",
          index: 3,
          rubric_criteria_id: "criteria_4",
          rubric_performance_rating_id: "rating_4",
          created_by: "admin",
        },
      ],
    },
  ],
};
